apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-janitor
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm
    kind: ClusterSecretStore
  target:
    name: ibmcloud-janitor-secret
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: 160fca4f-00e7-e60f-cb6b-1fd684b7766e
  - secretKey: k8s-key
    remoteRef:
      key: 1067b8e0-f051-3022-6379-20d9937aaa48
