apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-ibm-k8s-infra
spec:
  provider:
    ibm:
      serviceUrl: "https://5fb5cabf-7ab9-4ba8-9f58-85bf1b8c470e.us-south.secrets-manager.appdomain.cloud"
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: admin-ibm-cloud
            key: ADMIN_API_KEY
            namespace: test-pods
