periodics:
  - name: periodic-hypershift-powervs-cleanup
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: alpine:latest
          command:
            - /bin/sh
          envFrom:
            - secretRef:
                name: ibm-cloud-credentials-hypershift
          args:
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace

              wget -q -O /usr/local/bin/pvsadm https://github.com/ppc64le-cloud/pvsadm/releases/download/v0.1.1-alpha.7/pvsadm-linux-ppc64le
              chmod +x /usr/local/bin/pvsadm

              # cleanup all the vms created in rh-upstream-hypershift-clusterbot-pvs workspace before 24hrs
              pvsadm purge vms --instance-id 3fd2eae4-f67b-4a2d-a2fb-438bd6355eb4 --before 24h --ignore-errors --no-prompt
              # cleanup all the vms created in rh-upstream-hypershift-powervs-e2e-ci-pvs workspace before 24hrs
              pvsadm purge vms --instance-id bcfa4456-4be5-422a-b742-181f0cbe17d8 --before 24h --ignore-errors --no-prompt
              # cleanup all the vms created in rh-upstream-hypershift-agent-ci workspace before 24hrs
              pvsadm purge vms --instance-id d04e2b0c-58aa-4e64-85c1-ecb5ab00d03d --before 24h --regexp '[^bastion]' --ignore-errors --no-prompt
