periodics:
  - name: periodic-kubernetes-unit-test-ppc64le
    cluster: k8s-ppc64le-cluster
    labels:
      preset-golang-build: "true"
    decorate: true
    decoration_config:
      gcs_configuration:
        bucket: ppc64le-kubernetes
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
    cron: "0 1/3 * * *"
    extra_refs:
      - base_ref: master
        org: kubernetes
        repo: kubernetes
        workdir: true
    spec:
      containers:
        - image: quay.io/powercloud/all-in-one:0.7
          resources:
            requests:
              cpu: "5000m"
            limits:
              cpu: "5000m"
          command:
            - /bin/bash
          args:
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace

              export KUBE_TIMEOUT='--timeout=600s'
              export KUBE_KEEP_VERBOSE_TEST_OUTPUT=y
              export LOG_LEVEL=4
              wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_ppc64le
              chmod +x /usr/local/bin/yq
              pushd ./build/
              GOLANG_VERSION=`yq read dependencies.yaml 'dependencies(name==golang: upstream*).version'`
              popd
              url="https://storage.googleapis.com/golang/go${GOLANG_VERSION}.linux-ppc64le.tar.gz"
              wget -O go.tgz "$url" --progress=dot:giga
              rm -rf /usr/local/go
              tar -C /usr/local -xzf go.tgz
              make test KUBE_RACE=-race
  - name: periodic-kubernetes-containerd-conformance-test-ppc64le
    cluster: k8s-ppc64le-cluster
    labels:
      preset-ssh-bot: "true"
    decorate: true
    decoration_config:
      gcs_configuration:
        bucket: ppc64le-kubernetes
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
    cron: "0 2/3 * * *"
    extra_refs:
      - base_ref: master
        org: ppc64le-cloud
        repo: kubetest2-plugins
      - base_ref: master
        org: kubernetes-sigs
        repo: kubetest2
        workdir: true
    spec:
      containers:
        - image: quay.io/powercloud/all-in-one:0.7
          resources:
            requests:
              cpu: "4000m"
            limits:
              cpu: "4000m"
          command:
            - /bin/bash
          args:
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace

              export PATH=$GOPATH/bin:$PATH
              export GO111MODULE=on

              make install
              make install-tester-ginkgo

              pushd ../../ppc64le-cloud/kubetest2-plugins
              make install-deployer-tf
              popd

              TIMESTAMP=$(date +%s)
              K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/k8s-release-dev/ci/latest.txt)
              jq --arg key0 'k8s-build-version' --arg value0 $K8S_BUILD_VERSION '. | .[$key0]=$value0' <<<'{}' > $ARTIFACTS/metadata.json

              # kubectl needed for the e2e tests
              curl -sSL https://dl.k8s.io/ci/$K8S_BUILD_VERSION/bin/linux/`go env GOARCH`/kubectl > /usr/local/bin/kubectl
              chmod +x /usr/local/bin/kubectl

              set +o errexit
              kubetest2 tf --powervs-dns k8s-tests \
                --powervs-image-name centos-9-stream-20Gb \
                --powervs-region syd --powervs-zone syd05 \
                --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 \
                --powervs-ssh-key powercloud-bot-key \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --build-version $K8S_BUILD_VERSION \
                --cluster-name config1-$TIMESTAMP \
                --workers-count 2 \
                --up --auto-approve --retry-on-tf-failure 3 \
                --break-kubetest-on-upfail true \
                --powervs-memory 32 \
                --test=ginkgo -- --parallel 10 --test-package-dir ci --test-package-version $K8S_BUILD_VERSION --focus-regex='\[Conformance\]' --skip-regex='\[Serial\]'; rc1=$?
              export KUBECONFIG="$(pwd)/config1-$TIMESTAMP/kubeconfig"
              export ARTIFACTS=$ARTIFACTS/serial_tests_artifacts
              #Run Serial Conformance tests
              kubetest2 tf --powervs-region syd --powervs-zone syd05 \
                --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 \
                --ignore-cluster-dir true \
                --cluster-name config1-$TIMESTAMP \
                --down --auto-approve --ignore-destroy-errors \
                --test=ginkgo -- \
                --test-package-dir ci \
                --test-package-version $K8S_BUILD_VERSION --focus-regex='\[Serial\].*\[Conformance\]'; rc2=$?
              if [ $rc1 != 0 ]; then
                  echo "ERROR: Non Serial k8s Conformance tests exited with code: $rc1"
                  exit $rc1
              elif [ $rc2 != 0 ]; then
                  echo "ERROR: Serial k8s Conformance tests exited with code: $rc2"
                  exit $rc2
              fi

  - name: periodic-kubernetes-containerd-e2e-node-tests-ppc64le
    cluster: k8s-ppc64le-cluster
    labels:
      preset-golang-build: "true"
      preset-ssh-bot: "true"
    decorate: true
    decoration_config:
      gcs_configuration:
        bucket: ppc64le-kubernetes
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
      timeout: 2h
    cron: "0 3/3 * * *"
    extra_refs:
      - base_ref: master
        org: ppc64le-cloud
        repo: kubetest2-plugins
      - base_ref: master
        org: kubernetes-sigs
        repo: kubetest2
        workdir: true
    spec:
      containers:
        - image: quay.io/powercloud/all-in-one:0.7
          resources:
            requests:
              cpu: "4000m"
            limits:
              cpu: "4000m"
          command:
            - /bin/bash
          args:
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace

              export PATH=$GOPATH/bin:$PATH
              export GO111MODULE=on

              make install
              make install-tester-exec

              pushd ../../ppc64le-cloud/kubetest2-plugins
              make install-deployer-tf
              popd

              TIMESTAMP=$(date +%s)
              K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/k8s-release-dev/ci/latest.txt)
              jq --arg key0 'k8s-build-version' --arg value0 $K8S_BUILD_VERSION '. | .[$key0]=$value0' <<<'{}' > $ARTIFACTS/metadata.json

              # kubectl needed for the e2e tests
              curl -sSL https://dl.k8s.io/ci/$K8S_BUILD_VERSION/bin/linux/`go env GOARCH`/kubectl > /usr/local/bin/kubectl
              chmod +x /usr/local/bin/kubectl

              set +o errexit
              kubetest2 tf --powervs-dns k8s-tests \
                --powervs-image-name centos-9-stream-20Gb \
                --powervs-region syd --powervs-zone syd05 \
                --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 \
                --powervs-ssh-key powercloud-bot-key \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --cluster-name config3-$TIMESTAMP \
                --up --set-kubeconfig=false --auto-approve \
                --build-version $K8S_BUILD_VERSION --retry-on-tf-failure 3 \
                --break-kubetest-on-upfail true --powervs-memory 32 \
                --playbook k8s-node-remote.yml
              EXTERNAL_IP=`grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' $(pwd)/config3-$TIMESTAMP/hosts`
              kubetest2 tf --test=exec -- ssh -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP \
                "export SKIP='\[Flaky\]|\[Slow\]|\[Serial\]|Containers.Lifecycle.should|should.execute.readiness.probe.while.in.preStop' && /make-test-e2e-node.sh"; \
                rc=$?; scp -r -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP:/tmp/_artifacts $ARTIFACTS
              kubetest2 tf --powervs-region syd --powervs-zone syd05 \
                --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 \
                --ignore-cluster-dir true \
                --cluster-name config3-$TIMESTAMP \
                --down --auto-approve --ignore-destroy-errors
              [ $rc != 0 ] && echo "ERROR: E2ENode Test suite exited with code:$rc"; exit $rc
